# Generated by Django 4.2.3 on 2023-08-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Recipe_title')),
                ('image', models.CharField(max_length=200, verbose_name='Recipe_image_url')),
                ('recipe_url', models.CharField(max_length=300, verbose_name='Recipe_url')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Recipe_is_favorite')),
            ],
        ),
    ]
