# Generated by Django 4.2.3 on 2023-08-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonfish_recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foods',
            new_name='Food',
        ),
    ]
