# Generated by Django 4.2.3 on 2023-08-29 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moonfish_recipe', '0002_rename_foods_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='food',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
